version: "3.3"

services:
  redis:
    image: redis:latest
    restart: always
    volumes:
      - "./data/redis:/data"
    environment:
      - REDIS_PASSWORD="${REDIS_PASSWORD}"
      - REDIS_PORT='6379'
    ports:
      - "6379:6379"
